version: '3.8'

services:
  teacher-video-processor:
    build: .
    container_name: teacher-video-processor
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=INFO
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./temp:/app/temp
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加 Redis 用于任务队列（如果需要更复杂的任务管理）
  # redis:
  #   image: redis:7-alpine
  #   container_name: teacher-video-redis
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

networks:
  default:
    name: teacher-video-network